--- 
abstract: Dimension Reduction tool that relies on 'Octave'
author: 
  - Takeshi Miki <t.miki@nttr.co.jp>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Algorithm-DimReduction
no_index: 
  directory: 
    - inc
    - t
requires: 
  Class::Accessor::Fast: 0
  File::Copy: 0
  File::Temp: 0
  Storable: 0
version: 0.00001
